spring:
  application:
    name: server

  output:
    ansi:
      enabled: always

  datasource:
    url: [your url here]
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  mail:
    host: 
    username: 
    password: 
    protocol: 
    properties.mail.smtp.auth: 
    properties.mail.smtp.port: 
    properties.mail.smtp.starttls.enable: 
    properties.mail.smtp.starttls.required: 
    properties.mail.smtp.ssl.enable: 
    from: 
    default-encoding: 

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
    field-strategy: 0
